In [14]:
# Project 2: Student Gradebook Analyzer
import pandas as pd
import numpy as np
data = {
    "Name": ["Aman", "siya", "Rahul", "Sneha", "Karan"],
    "Assignment1": [85, 92, 76, 88, 65],
    "Assignment2": [78, 95, 80, 84, 70],
    "Assignment3": [90, 89, 70, 91, 68],
    "Assignment4": [88, 94, 75, 90, 72]
}

df = pd.DataFrame(data)

df

    Name  Assignment1  Assignment2  Assignment3  Assignment4
0   Aman           85           78           90           88
1   siya           92           95           89           94
2  Rahul           76           80           70           75
3  Sneha           88           84           91           90
4  Karan           65           70           68           72

In [15]:
# Save DataFrame to a CSV file

df.to_csv("gradebook.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [16]:
# Read the CSV file

df = pd.read_csv("gradebook.csv")

print("Data Loaded Successfully:")
df

Data Loaded Successfully:

    Name  Assignment1  Assignment2  Assignment3  Assignment4
0   Aman           85           78           90           88
1   siya           92           95           89           94
2  Rahul           76           80           70           75
3  Sneha           88           84           91           90
4  Karan           65           70           68           72

In [17]:
# Calculate student statistics

assignments = ["Assignment1", "Assignment2", "Assignment3", "Assignment4"]

df["Average"] = df[assignments].mean(axis=1)
df["Median"] = df[assignments].median(axis=1)
df["Maximum"] = df[assignments].max(axis=1)
df["Minimum"] = df[assignments].min(axis=1)

print("Student Statistics:")
df

Student Statistics:

,Name,Assignment1,Assignment2,Assignment3,Assignment4,Average,Median,Maximum,Minimum
0,Aman,85,78,90,88,85.25,86.5,90,78
1,siya,92,95,89,94,92.50,93.0,95,89
2,Rahul,76,80,70,75,75.25,75.5,80,70
3,Sneha,88,84,91,90,88.25,89.0,91,84
4,Karan,65,70,68,72,68.75,69.0,72,65

In [18]:
# Calculate assignment statistics

print("Assignment Statistics\n")

for assignment in assignments:
    print(assignment)
    print("Average :", df[assignment].mean())
    print("Median  :", df[assignment].median())
    print("Maximum :", df[assignment].max())
    print("Minimum :", df[assignment].min())
    print("----------------------------")

Assignment Statistics

Assignment1
Average : 81.2
Median  : 85.0
Maximum : 92
Minimum : 65
----------------------------
Assignment2
Average : 81.4
Median  : 80.0
Maximum : 95
Minimum : 70
----------------------------
Assignment3
Average : 81.6
Median  : 89.0
Maximum : 91
Minimum : 68
----------------------------
Assignment4
Average : 83.8
Median  : 88.0
Maximum : 94
Minimum : 72
----------------------------

In [19]:
# Sort students by average score

sorted_df = df.sort_values(by="Average", ascending=False)

print("Students Sorted by Average Score:")
sorted_df

Students Sorted by Average Score:

,Name,Assignment1,Assignment2,Assignment3,Assignment4,Average,Median,Maximum,Minimum
1,siya,92,95,89,94,92.50,93.0,95,89
3,Sneha,88,84,91,90,88.25,89.0,91,84
0,Aman,85,78,90,88,85.25,86.5,90,78
2,Rahul,76,80,70,75,75.25,75.5,80,70
4,Karan,65,70,68,72,68.75,69.0,72,65

In [20]:
# Identify the top performer

top_student = sorted_df.iloc[0]

print("Top Performer")
print("Name :", top_student["Name"])
print("Average Score :", round(top_student["Average"], 2))

Top Performer
Name : siya
Average Score : 92.5

In [21]:
# NumPy operations

scores = df[assignments].to_numpy()

print("Overall Statistics")

print("Overall Average :", np.mean(scores))
print("Overall Highest :", np.max(scores))
print("Overall Lowest :", np.min(scores))
print("Standard Deviation :", round(np.std(scores), 2))

Overall Statistics
Overall Average : 82.0
Overall Highest : 95
Overall Lowest : 65
Standard Deviation : 9.31

In [22]:
# Display final DataFrame

print("Final Student Gradebook:")
df

Final Student Gradebook:

,Name,Assignment1,Assignment2,Assignment3,Assignment4,Average,Median,Maximum,Minimum
0,Aman,85,78,90,88,85.25,86.5,90,78
1,siya,92,95,89,94,92.50,93.0,95,89
2,Rahul,76,80,70,75,75.25,75.5,80,70
3,Sneha,88,84,91,90,88.25,89.0,91,84
4,Karan,65,70,68,72,68.75,69.0,72,65